### ISSUE TITLE
Setup not working

### ISSUE THREAD

**Issue by nikosT** [oar-team/oar-docker-compose#2]
Installation does not seem to work anymore

**Comment by adfaure** [comment]
Hello, thanks for the report.

Could you provide us more details about what you tried, and the errors that you have ?

Thanks.

**Comment by nikosT** [comment]
After running the command: `docker exec -u user1 -ti dev_frontend_1 bash`, then, inside the docker I execute `oarsub -I` and I receive the following error:

```bash
docker exec -u user1 -ti dev_frontend_1 bash
user1@frontend:/$ oarsub -I
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3256, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 597, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  database "oar" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/oar/.oarsub", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/oar/cli/oarsub.py", line 622, in cli
    (error, job_id_lst) = submission.submit()
  File "/usr/local/lib/python3.9/dist-packages/oar/lib/submission.py", line 1451, in submit
    (err, job_id_lst) = add_micheline_jobs(
  File "/usr/local/lib/python3.9/dist-packages/oar/lib/submission.py", line 1082, in add_micheline_jobs
    db.query(AdmissionRule.rule)
  File "/usr/local/lib/python3.9/dist-packages/oar/lib/database.py", line 206, in query
    return self.session.query
  File "/usr/local/lib/python3.9/dist-packages/oar/lib/database.py", line 108, in __get__
    obj.reflect(bind=self._sessions[obj]().bind)
  File "/usr/local/lib/python3.9/dist-packages/oar/lib/database.py", line 229, in reflect
    self.create_all(bind=bind)
  File "/usr/local/lib/python3.9/dist-packages/oar/lib/database.py", line 238, in create_all
    self.metadata.create_all(bind=bind, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/sql/schema.py", line 4864, in create_all
    bind._run_ddl_visitor(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3122, in _run_ddl_visitor
    with self.begin() as conn:
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3038, in begin
    conn = self.connect(close_with_result=close_with_result)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3210, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3289, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3259, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 2106, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 3256, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 597, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  database "oar" does not exist

(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

Additionally, if I run `docker exec --user oar --env OARCONFFILE=/etc/oar/oar.conf dev_frontend_1 uvicorn oar.api.app:app --port 8001 --host 0.0.0.0` as mentioned in README, it does not find the user, so I tried with `user1`, but then I receive the message:
```bash
docker exec --user user1 --env OARCONFFILE=/etc/oar/oar.conf dev_frontend_1 uvicorn oar.api.app:app --port 8001 --host 0.0.0.0
Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/main.py", line 371, in main
    run(app, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/main.py", line 393, in run
    server.run()
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/server.py", line 50, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/server.py", line 57, in serve
    config.load()
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/config.py", line 318, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/importer.py", line 22, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/dist-packages/oar/api/app.py", line 6, in <module>
    from oar.lib import config, db
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "/usr/local/lib/python3.9/dist-packages/oar/lib/__init__.py", line 98, in __getattr__
    module = __import__(object_origins[name], None, None, [name])
  File "/usr/local/lib/python3.9/dist-packages/oar/lib/globals.py", line 13, in <module>
    config.load_file(os.environ["OARCONFFILE"])
  File "/usr/local/lib/python3.9/dist-packages/oar/lib/configuration.py", line 175, in load_file
    reraise(exc_type, exc_value, tb.tb_next)
  File "/usr/local/lib/python3.9/dist-packages/oar/lib/utils.py", line 69, in reraise
    raise value.with_traceback(tb)
PermissionError: [Errno 13] Unable to load configuration file (Permission denied): '/etc/oar/oar.conf'
```
I tried with `sudo` too.

**Comment by adfaure** [comment]
Hello, 

Indeed, something that I have to document is that when you run the dockers, an installation script is executed in systemd, called provisioning.  You can see its activity with `systemctl  | grep oardocker-provision.service` when you are in the docker.

This script is in charge of installing OAR, and you have to wait for it to finish in order to be able to run a job.

Does that help ?

**Comment by nikosT** [comment]
Hi @adfaure,

Thank you for your reply! Yes, now it works. I can see the swagger interface.

**Comment by adfaure** [comment]
Thank you for your update, I'll close this issue when I documented it in the readme.
